version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=modbus_db
      - MODBUS_HOST=modbus_simulator
      - MODBUS_PORT=5020
      - READING_INTERVAL=5000
    depends_on:
      - db
    networks:
      - modbus-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=modbus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - modbus-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  modbus-network:
    driver: bridge

volumes:
  postgres_data:
